/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (p11tool-args.c)
 *  
 *  It has been AutoGen-ed  February 24, 2012 at 05:06:29 PM by AutoGen 5.15pre10
 *  From the definitions    p11tool-args.def
 *  and the template file   options
 *
 * Generated from AutoOpts 36:2:11 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the p11tool author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The p11tool program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 2000-2012 Free Software Foundation, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  p11tool is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  p11tool is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>

#define OPTION_CODE_COMPILE 1
#include "p11tool-args.h"
#include <errno.h>
#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

extern int optionAlias(tOptions * o, tOptDesc* od, unsigned int alias);

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (p11tool_opt_strs+0)
#define zLicenseDescrip (p11tool_opt_strs+275)

extern tUsageProc optionUsage;

#ifndef NULL
#  define NULL 0
#endif

/*
 *  p11tool option static const strings
 */
static char const p11tool_opt_strs[3232] =
/*     0 */ "p11tool 3.0.14\n"
            "Copyright (C) 2000-2012 Free Software Foundation, all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   275 */ "p11tool is free software: you can redistribute it and/or modify it under\n"
            "the terms of the GNU General Public License as published by the Free\n"
            "Software Foundation, either version 3 of the License, or (at your option)\n"
            "any later version.\n\n"
            "p11tool is distributed in the hope that it will be useful, but WITHOUT\n"
            "ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or\n"
            "FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License\n"
            "for more details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   878 */ "Enable debugging.\0"
/*   896 */ "DEBUG\0"
/*   902 */ "debug\0"
/*   908 */ "Output file\0"
/*   920 */ "OUTFILE\0"
/*   928 */ "outfile\0"
/*   936 */ "List all available tokens\0"
/*   962 */ "LIST_TOKENS\0"
/*   974 */ "list-tokens\0"
/*   986 */ "Export the object specified by the URL\0"
/*  1025 */ "EXPORT\0"
/*  1032 */ "export\0"
/*  1039 */ "List all available mechanisms in a token\0"
/*  1080 */ "LIST_MECHANISMS\0"
/*  1096 */ "list-mechanisms\0"
/*  1112 */ "List all available objects in a token\0"
/*  1150 */ "LIST_ALL\0"
/*  1159 */ "list-all\0"
/*  1168 */ "List all available certificates in a token\0"
/*  1211 */ "LIST_ALL_CERTS\0"
/*  1226 */ "list-all-certs\0"
/*  1241 */ "List all certificates that have an associated private key\0"
/*  1299 */ "LIST_CERTS\0"
/*  1310 */ "list-certs\0"
/*  1321 */ "List all available private keys in a token\0"
/*  1364 */ "LIST_ALL_PRIVKEYS\0"
/*  1382 */ "list-all-privkeys\0"
/*  1400 */ "List all available certificates marked as trusted\0"
/*  1450 */ "LIST_ALL_TRUSTED\0"
/*  1467 */ "list-all-trusted\0"
/*  1484 */ "Initializes a PKCS #11 token\0"
/*  1513 */ "INITIALIZE\0"
/*  1524 */ "initialize\0"
/*  1535 */ "Writes the loaded objects to a PKCS #11 token\0"
/*  1581 */ "WRITE\0"
/*  1587 */ "write\0"
/*  1593 */ "Deletes the objects matching the PKCS #11 URL\0"
/*  1639 */ "DELETE\0"
/*  1646 */ "delete\0"
/*  1653 */ "Generates an RSA private-public key pair on the specified token\0"
/*  1717 */ "GENERATE_RSA\0"
/*  1730 */ "generate-rsa\0"
/*  1743 */ "GENERATE_DSA\0"
/*  1756 */ "generate-dsa\0"
/*  1769 */ "GENERATE_ECC\0"
/*  1782 */ "generate-ecc\0"
/*  1795 */ "Sets a label for the write operation\0"
/*  1832 */ "LABEL\0"
/*  1838 */ "label\0"
/*  1844 */ "Marks the object to be written as trusted\0"
/*  1886 */ "TRUSTED\0"
/*  1894 */ "no-trusted\0"
/*  1905 */ "no\0"
/*  1908 */ "Marks the object to be written as private\0"
/*  1950 */ "PRIVATE\0"
/*  1958 */ "no-private\0"
/*  1969 */ "Force login to token\0"
/*  1990 */ "LOGIN\0"
/*  1996 */ "no-login\0"
/*  2005 */ "Print detailed URLs\0"
/*  2025 */ "DETAILED_URL\0"
/*  2038 */ "no-detailed-url\0"
/*  2054 */ "Provide a hex encoded secret key\0"
/*  2087 */ "SECRET_KEY\0"
/*  2098 */ "secret-key\0"
/*  2109 */ "Private key file to use\0"
/*  2133 */ "LOAD_PRIVKEY\0"
/*  2146 */ "load-privkey\0"
/*  2159 */ "Public key file to use\0"
/*  2182 */ "LOAD_PUBKEY\0"
/*  2194 */ "load-pubkey\0"
/*  2206 */ "Certificate file to use\0"
/*  2230 */ "LOAD_CERTIFICATE\0"
/*  2247 */ "load-certificate\0"
/*  2264 */ "Use PKCS #8 format for private keys\0"
/*  2300 */ "PKCS8\0"
/*  2306 */ "pkcs8\0"
/*  2312 */ "Specify the number of bits for key generate\0"
/*  2356 */ "BITS\0"
/*  2361 */ "bits\0"
/*  2366 */ "Specify the security level [low|legacy|normal|high|ultra].\0"
/*  2425 */ "SEC_PARAM\0"
/*  2435 */ "sec-param\0"
/*  2445 */ "Use DER/RAW format for input certificates and private keys\0"
/*  2504 */ "INDER\0"
/*  2510 */ "no-inder\0"
/*  2519 */ "This is an alias for 'inder'\0"
/*  2548 */ "inraw\0"
/*  2554 */ "Specify the PKCS #11 provider library\0"
/*  2592 */ "PROVIDER\0"
/*  2601 */ "provider\0"
/*  2610 */ "Display extended usage information and exit\0"
/*  2654 */ "help\0"
/*  2659 */ "Extended usage information passed thru pager\0"
/*  2704 */ "more-help\0"
/*  2714 */ "Output version information and exit\0"
/*  2750 */ "version\0"
/*  2758 */ "P11TOOL\0"
/*  2766 */ "p11tool - GnuTLS PKCS #11 tool - Ver. 3.0.14\n"
            "USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [url]\n\0"
/*  2875 */ "bug-gnutls@gnu.org\0"
/*  2894 */ "\n\n\0"
/*  2897 */ "\n"
            "Program that allows handling data from PKCS #11 smart cards and security\n"
            "modules.\n\n"
            "To use PKCS #11 tokens with gnutls the configuration file\n"
            "/etc/gnutls/pkcs11.conf has to exist and contain a number of lines of\n"
            "the form 'load=/usr/lib/opensc-pkcs11.so'.\n\0"
/*  3153 */ "p11tool 3.0.14\0"
/*  3168 */ "p11tool [options] [url]\n"
            "p11tool --help for usage instructions.\n";

/*
 *  debug option description:
 */
#define DEBUG_DESC      (p11tool_opt_strs+878)
#define DEBUG_NAME      (p11tool_opt_strs+896)
#define DEBUG_name      (p11tool_opt_strs+902)
#define DEBUG_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  outfile option description:
 */
#define OUTFILE_DESC      (p11tool_opt_strs+908)
#define OUTFILE_NAME      (p11tool_opt_strs+920)
#define OUTFILE_name      (p11tool_opt_strs+928)
#define OUTFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  list-tokens option description:
 */
#define LIST_TOKENS_DESC      (p11tool_opt_strs+936)
#define LIST_TOKENS_NAME      (p11tool_opt_strs+962)
#define LIST_TOKENS_name      (p11tool_opt_strs+974)
#define LIST_TOKENS_FLAGS     (OPTST_DISABLED)

/*
 *  export option description:
 */
#define EXPORT_DESC      (p11tool_opt_strs+986)
#define EXPORT_NAME      (p11tool_opt_strs+1025)
#define EXPORT_name      (p11tool_opt_strs+1032)
#define EXPORT_FLAGS     (OPTST_DISABLED)

/*
 *  list-mechanisms option description:
 */
#define LIST_MECHANISMS_DESC      (p11tool_opt_strs+1039)
#define LIST_MECHANISMS_NAME      (p11tool_opt_strs+1080)
#define LIST_MECHANISMS_name      (p11tool_opt_strs+1096)
#define LIST_MECHANISMS_FLAGS     (OPTST_DISABLED)

/*
 *  list-all option description:
 */
#define LIST_ALL_DESC      (p11tool_opt_strs+1112)
#define LIST_ALL_NAME      (p11tool_opt_strs+1150)
#define LIST_ALL_name      (p11tool_opt_strs+1159)
#define LIST_ALL_FLAGS     (OPTST_DISABLED)

/*
 *  list-all-certs option description:
 */
#define LIST_ALL_CERTS_DESC      (p11tool_opt_strs+1168)
#define LIST_ALL_CERTS_NAME      (p11tool_opt_strs+1211)
#define LIST_ALL_CERTS_name      (p11tool_opt_strs+1226)
#define LIST_ALL_CERTS_FLAGS     (OPTST_DISABLED)

/*
 *  list-certs option description:
 */
#define LIST_CERTS_DESC      (p11tool_opt_strs+1241)
#define LIST_CERTS_NAME      (p11tool_opt_strs+1299)
#define LIST_CERTS_name      (p11tool_opt_strs+1310)
#define LIST_CERTS_FLAGS     (OPTST_DISABLED)

/*
 *  list-all-privkeys option description:
 */
#define LIST_ALL_PRIVKEYS_DESC      (p11tool_opt_strs+1321)
#define LIST_ALL_PRIVKEYS_NAME      (p11tool_opt_strs+1364)
#define LIST_ALL_PRIVKEYS_name      (p11tool_opt_strs+1382)
#define LIST_ALL_PRIVKEYS_FLAGS     (OPTST_DISABLED)

/*
 *  list-all-trusted option description:
 */
#define LIST_ALL_TRUSTED_DESC      (p11tool_opt_strs+1400)
#define LIST_ALL_TRUSTED_NAME      (p11tool_opt_strs+1450)
#define LIST_ALL_TRUSTED_name      (p11tool_opt_strs+1467)
#define LIST_ALL_TRUSTED_FLAGS     (OPTST_DISABLED)

/*
 *  initialize option description:
 */
#define INITIALIZE_DESC      (p11tool_opt_strs+1484)
#define INITIALIZE_NAME      (p11tool_opt_strs+1513)
#define INITIALIZE_name      (p11tool_opt_strs+1524)
#define INITIALIZE_FLAGS     (OPTST_DISABLED)

/*
 *  write option description:
 */
#define WRITE_DESC      (p11tool_opt_strs+1535)
#define WRITE_NAME      (p11tool_opt_strs+1581)
#define WRITE_name      (p11tool_opt_strs+1587)
#define WRITE_FLAGS     (OPTST_DISABLED)

/*
 *  delete option description:
 */
#define DELETE_DESC      (p11tool_opt_strs+1593)
#define DELETE_NAME      (p11tool_opt_strs+1639)
#define DELETE_name      (p11tool_opt_strs+1646)
#define DELETE_FLAGS     (OPTST_DISABLED)

/*
 *  generate-rsa option description:
 */
#define GENERATE_RSA_DESC      (p11tool_opt_strs+1653)
#define GENERATE_RSA_NAME      (p11tool_opt_strs+1717)
#define GENERATE_RSA_name      (p11tool_opt_strs+1730)
#define GENERATE_RSA_FLAGS     (OPTST_DISABLED)

/*
 *  generate-dsa option description:
 */
#define GENERATE_DSA_DESC      (p11tool_opt_strs+1653)
#define GENERATE_DSA_NAME      (p11tool_opt_strs+1743)
#define GENERATE_DSA_name      (p11tool_opt_strs+1756)
#define GENERATE_DSA_FLAGS     (OPTST_DISABLED)

/*
 *  generate-ecc option description:
 */
#define GENERATE_ECC_DESC      (p11tool_opt_strs+1653)
#define GENERATE_ECC_NAME      (p11tool_opt_strs+1769)
#define GENERATE_ECC_name      (p11tool_opt_strs+1782)
#define GENERATE_ECC_FLAGS     (OPTST_DISABLED)

/*
 *  label option description:
 */
#define LABEL_DESC      (p11tool_opt_strs+1795)
#define LABEL_NAME      (p11tool_opt_strs+1832)
#define LABEL_name      (p11tool_opt_strs+1838)
#define LABEL_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  trusted option description:
 */
#define TRUSTED_DESC      (p11tool_opt_strs+1844)
#define TRUSTED_NAME      (p11tool_opt_strs+1886)
#define NOT_TRUSTED_name  (p11tool_opt_strs+1894)
#define NOT_TRUSTED_PFX   (p11tool_opt_strs+1905)
#define TRUSTED_name      (NOT_TRUSTED_name + 3)
#define TRUSTED_FLAGS     (OPTST_DISABLED)

/*
 *  private option description:
 */
#define PRIVATE_DESC      (p11tool_opt_strs+1908)
#define PRIVATE_NAME      (p11tool_opt_strs+1950)
#define NOT_PRIVATE_name  (p11tool_opt_strs+1958)
#define NOT_PRIVATE_PFX   (p11tool_opt_strs+1905)
#define PRIVATE_name      (NOT_PRIVATE_name + 3)
#define PRIVATE_FLAGS     (OPTST_INITENABLED)

/*
 *  login option description:
 */
#define LOGIN_DESC      (p11tool_opt_strs+1969)
#define LOGIN_NAME      (p11tool_opt_strs+1990)
#define NOT_LOGIN_name  (p11tool_opt_strs+1996)
#define NOT_LOGIN_PFX   (p11tool_opt_strs+1905)
#define LOGIN_name      (NOT_LOGIN_name + 3)
#define LOGIN_FLAGS     (OPTST_DISABLED)

/*
 *  detailed-url option description:
 */
#define DETAILED_URL_DESC      (p11tool_opt_strs+2005)
#define DETAILED_URL_NAME      (p11tool_opt_strs+2025)
#define NOT_DETAILED_URL_name  (p11tool_opt_strs+2038)
#define NOT_DETAILED_URL_PFX   (p11tool_opt_strs+1905)
#define DETAILED_URL_name      (NOT_DETAILED_URL_name + 3)
#define DETAILED_URL_FLAGS     (OPTST_DISABLED)

/*
 *  secret-key option description:
 */
#define SECRET_KEY_DESC      (p11tool_opt_strs+2054)
#define SECRET_KEY_NAME      (p11tool_opt_strs+2087)
#define SECRET_KEY_name      (p11tool_opt_strs+2098)
#define SECRET_KEY_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  load-privkey option description:
 */
#define LOAD_PRIVKEY_DESC      (p11tool_opt_strs+2109)
#define LOAD_PRIVKEY_NAME      (p11tool_opt_strs+2133)
#define LOAD_PRIVKEY_name      (p11tool_opt_strs+2146)
#define LOAD_PRIVKEY_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_FILE))

/*
 *  load-pubkey option description:
 */
#define LOAD_PUBKEY_DESC      (p11tool_opt_strs+2159)
#define LOAD_PUBKEY_NAME      (p11tool_opt_strs+2182)
#define LOAD_PUBKEY_name      (p11tool_opt_strs+2194)
#define LOAD_PUBKEY_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_FILE))

/*
 *  load-certificate option description:
 */
#define LOAD_CERTIFICATE_DESC      (p11tool_opt_strs+2206)
#define LOAD_CERTIFICATE_NAME      (p11tool_opt_strs+2230)
#define LOAD_CERTIFICATE_name      (p11tool_opt_strs+2247)
#define LOAD_CERTIFICATE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_FILE))

/*
 *  pkcs8 option description:
 */
#define PKCS8_DESC      (p11tool_opt_strs+2264)
#define PKCS8_NAME      (p11tool_opt_strs+2300)
#define PKCS8_name      (p11tool_opt_strs+2306)
#define PKCS8_FLAGS     (OPTST_DISABLED)

/*
 *  bits option description:
 */
#define BITS_DESC      (p11tool_opt_strs+2312)
#define BITS_NAME      (p11tool_opt_strs+2356)
#define BITS_name      (p11tool_opt_strs+2361)
#define BITS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  sec-param option description:
 */
#define SEC_PARAM_DESC      (p11tool_opt_strs+2366)
#define SEC_PARAM_NAME      (p11tool_opt_strs+2425)
#define SEC_PARAM_name      (p11tool_opt_strs+2435)
#define SEC_PARAM_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  inder option description:
 */
#define INDER_DESC      (p11tool_opt_strs+2445)
#define INDER_NAME      (p11tool_opt_strs+2504)
#define NOT_INDER_name  (p11tool_opt_strs+2510)
#define NOT_INDER_PFX   (p11tool_opt_strs+1905)
#define INDER_name      (NOT_INDER_name + 3)
#define INDER_FLAGS     (OPTST_DISABLED)

/*
 *  inraw option description:
 */
#define INRAW_DESC    (p11tool_opt_strs+2519)
#define INRAW_NAME    NULL
#define INRAW_name    (p11tool_opt_strs+2548)
#define INRAW_FLAGS     (INDER_FLAGS | OPTST_ALIAS)

/*
 *  provider option description:
 */
#define PROVIDER_DESC      (p11tool_opt_strs+2554)
#define PROVIDER_NAME      (p11tool_opt_strs+2592)
#define PROVIDER_name      (p11tool_opt_strs+2601)
#define PROVIDER_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_FILE))

/*
 *  Help/More_Help/Version option descriptions:
 */
#define HELP_DESC       (p11tool_opt_strs+2610)
#define HELP_name       (p11tool_opt_strs+2654)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (p11tool_opt_strs+2659)
#define MORE_HELP_name  (p11tool_opt_strs+2704)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#ifdef NO_OPTIONAL_OPT_ARGS
#  define VER_FLAGS     (OPTST_IMM | OPTST_NO_INIT)
#else
#  define VER_FLAGS     (OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | \
                         OPTST_ARG_OPTIONAL | OPTST_IMM | OPTST_NO_INIT)
#endif
#define VER_DESC        (p11tool_opt_strs+2714)
#define VER_name        (p11tool_opt_strs+2750)
/*
 *  Declare option callback procedures
 */
extern tOptProc
    optionBooleanVal,   optionNestedVal,    optionNumericVal,
    optionPagedUsage,   optionPrintVersion, optionResetOpt,
    optionStackArg,     optionTimeDate,     optionTimeVal,
    optionUnstackArg,   optionVendorOption;
static tOptProc
    doOptDebug,            doOptInraw,            doOptLoad_Certificate,
    doOptLoad_Privkey,     doOptLoad_Pubkey,      doOptProvider,
    doUsageOpt;
#define VER_PROC        optionPrintVersion

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the P11tool Option Descriptions.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, VALUE_OPT_DEBUG,
     /* equiv idx, value */ 0, VALUE_OPT_DEBUG,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DEBUG_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --debug */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptDebug,
     /* desc, NAME, name */ DEBUG_DESC, DEBUG_NAME, DEBUG_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_OUTFILE,
     /* equiv idx, value */ 1, VALUE_OPT_OUTFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OUTFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --outfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ OUTFILE_DESC, OUTFILE_NAME, OUTFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_LIST_TOKENS,
     /* equiv idx, value */ 2, VALUE_OPT_LIST_TOKENS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LIST_TOKENS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --list-tokens */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LIST_TOKENS_DESC, LIST_TOKENS_NAME, LIST_TOKENS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_EXPORT,
     /* equiv idx, value */ 3, VALUE_OPT_EXPORT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ EXPORT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --export */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ EXPORT_DESC, EXPORT_NAME, EXPORT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_LIST_MECHANISMS,
     /* equiv idx, value */ 4, VALUE_OPT_LIST_MECHANISMS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LIST_MECHANISMS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --list-mechanisms */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LIST_MECHANISMS_DESC, LIST_MECHANISMS_NAME, LIST_MECHANISMS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 5, VALUE_OPT_LIST_ALL,
     /* equiv idx, value */ 5, VALUE_OPT_LIST_ALL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LIST_ALL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --list-all */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LIST_ALL_DESC, LIST_ALL_NAME, LIST_ALL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_LIST_ALL_CERTS,
     /* equiv idx, value */ 6, VALUE_OPT_LIST_ALL_CERTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LIST_ALL_CERTS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --list-all-certs */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LIST_ALL_CERTS_DESC, LIST_ALL_CERTS_NAME, LIST_ALL_CERTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_LIST_CERTS,
     /* equiv idx, value */ 7, VALUE_OPT_LIST_CERTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LIST_CERTS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --list-certs */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LIST_CERTS_DESC, LIST_CERTS_NAME, LIST_CERTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 8, VALUE_OPT_LIST_ALL_PRIVKEYS,
     /* equiv idx, value */ 8, VALUE_OPT_LIST_ALL_PRIVKEYS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LIST_ALL_PRIVKEYS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --list-all-privkeys */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LIST_ALL_PRIVKEYS_DESC, LIST_ALL_PRIVKEYS_NAME, LIST_ALL_PRIVKEYS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 9, VALUE_OPT_LIST_ALL_TRUSTED,
     /* equiv idx, value */ 9, VALUE_OPT_LIST_ALL_TRUSTED,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LIST_ALL_TRUSTED_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --list-all-trusted */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LIST_ALL_TRUSTED_DESC, LIST_ALL_TRUSTED_NAME, LIST_ALL_TRUSTED_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 10, VALUE_OPT_INITIALIZE,
     /* equiv idx, value */ 10, VALUE_OPT_INITIALIZE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INITIALIZE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --initialize */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ INITIALIZE_DESC, INITIALIZE_NAME, INITIALIZE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 11, VALUE_OPT_WRITE,
     /* equiv idx, value */ 11, VALUE_OPT_WRITE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ WRITE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --write */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ WRITE_DESC, WRITE_NAME, WRITE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 12, VALUE_OPT_DELETE,
     /* equiv idx, value */ 12, VALUE_OPT_DELETE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DELETE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --delete */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DELETE_DESC, DELETE_NAME, DELETE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 13, VALUE_OPT_GENERATE_RSA,
     /* equiv idx, value */ 13, VALUE_OPT_GENERATE_RSA,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ GENERATE_RSA_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --generate-rsa */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ GENERATE_RSA_DESC, GENERATE_RSA_NAME, GENERATE_RSA_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 14, VALUE_OPT_GENERATE_DSA,
     /* equiv idx, value */ 14, VALUE_OPT_GENERATE_DSA,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ GENERATE_DSA_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --generate-dsa */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ GENERATE_DSA_DESC, GENERATE_DSA_NAME, GENERATE_DSA_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 15, VALUE_OPT_GENERATE_ECC,
     /* equiv idx, value */ 15, VALUE_OPT_GENERATE_ECC,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ GENERATE_ECC_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --generate-ecc */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ GENERATE_ECC_DESC, GENERATE_ECC_NAME, GENERATE_ECC_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 16, VALUE_OPT_LABEL,
     /* equiv idx, value */ 16, VALUE_OPT_LABEL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LABEL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --label */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LABEL_DESC, LABEL_NAME, LABEL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 17, VALUE_OPT_TRUSTED,
     /* equiv idx, value */ 17, VALUE_OPT_TRUSTED,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TRUSTED_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --trusted */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TRUSTED_DESC, TRUSTED_NAME, TRUSTED_name,
     /* disablement strs */ NOT_TRUSTED_name, NOT_TRUSTED_PFX },

  {  /* entry idx, value */ 18, VALUE_OPT_PRIVATE,
     /* equiv idx, value */ 18, VALUE_OPT_PRIVATE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PRIVATE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --private */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PRIVATE_DESC, PRIVATE_NAME, PRIVATE_name,
     /* disablement strs */ NOT_PRIVATE_name, NOT_PRIVATE_PFX },

  {  /* entry idx, value */ 19, VALUE_OPT_LOGIN,
     /* equiv idx, value */ 19, VALUE_OPT_LOGIN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOGIN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --login */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LOGIN_DESC, LOGIN_NAME, LOGIN_name,
     /* disablement strs */ NOT_LOGIN_name, NOT_LOGIN_PFX },

  {  /* entry idx, value */ 20, VALUE_OPT_DETAILED_URL,
     /* equiv idx, value */ 20, VALUE_OPT_DETAILED_URL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DETAILED_URL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --detailed-url */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DETAILED_URL_DESC, DETAILED_URL_NAME, DETAILED_URL_name,
     /* disablement strs */ NOT_DETAILED_URL_name, NOT_DETAILED_URL_PFX },

  {  /* entry idx, value */ 21, VALUE_OPT_SECRET_KEY,
     /* equiv idx, value */ 21, VALUE_OPT_SECRET_KEY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SECRET_KEY_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --secret-key */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SECRET_KEY_DESC, SECRET_KEY_NAME, SECRET_KEY_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 22, VALUE_OPT_LOAD_PRIVKEY,
     /* equiv idx, value */ 22, VALUE_OPT_LOAD_PRIVKEY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOAD_PRIVKEY_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --load-privkey */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoad_Privkey,
     /* desc, NAME, name */ LOAD_PRIVKEY_DESC, LOAD_PRIVKEY_NAME, LOAD_PRIVKEY_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 23, VALUE_OPT_LOAD_PUBKEY,
     /* equiv idx, value */ 23, VALUE_OPT_LOAD_PUBKEY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOAD_PUBKEY_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --load-pubkey */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoad_Pubkey,
     /* desc, NAME, name */ LOAD_PUBKEY_DESC, LOAD_PUBKEY_NAME, LOAD_PUBKEY_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 24, VALUE_OPT_LOAD_CERTIFICATE,
     /* equiv idx, value */ 24, VALUE_OPT_LOAD_CERTIFICATE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOAD_CERTIFICATE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --load-certificate */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoad_Certificate,
     /* desc, NAME, name */ LOAD_CERTIFICATE_DESC, LOAD_CERTIFICATE_NAME, LOAD_CERTIFICATE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 25, VALUE_OPT_PKCS8,
     /* equiv idx, value */ 25, VALUE_OPT_PKCS8,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PKCS8_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pkcs8 */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PKCS8_DESC, PKCS8_NAME, PKCS8_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 26, VALUE_OPT_BITS,
     /* equiv idx, value */ 26, VALUE_OPT_BITS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BITS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --bits */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ BITS_DESC, BITS_NAME, BITS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 27, VALUE_OPT_SEC_PARAM,
     /* equiv idx, value */ 27, VALUE_OPT_SEC_PARAM,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SEC_PARAM_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --sec-param */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SEC_PARAM_DESC, SEC_PARAM_NAME, SEC_PARAM_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 28, VALUE_OPT_INDER,
     /* equiv idx, value */ 28, VALUE_OPT_INDER,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INDER_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --inder */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ INDER_DESC, INDER_NAME, INDER_name,
     /* disablement strs */ NOT_INDER_name, NOT_INDER_PFX },

  {  /* entry idx, value */ 29, VALUE_OPT_INRAW,
     /* equiv idx, value */ 29, VALUE_OPT_INRAW,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INRAW_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --inraw */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptInraw,
     /* desc, NAME, name */ INRAW_DESC, INRAW_NAME, INRAW_name,
     /* disablement strs */ 0, 0 },

  {  /* entry idx, value */ 30, VALUE_OPT_PROVIDER,
     /* equiv idx, value */ 30, VALUE_OPT_PROVIDER,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PROVIDER_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --provider */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptProvider,
     /* desc, NAME, name */ PROVIDER_DESC, PROVIDER_NAME, PROVIDER_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VER_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ VER_PROC,
     /* desc, NAME, name */ VER_DESC, NULL, VER_name,
     /* disablement strs */ NULL, NULL },



  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL }
};


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the P11tool Option Environment
 */
#define zPROGNAME       (p11tool_opt_strs+2758)
#define zUsageTitle     (p11tool_opt_strs+2766)
#define zRcName         NULL
#define apzHomeList     NULL
#define zBugsAddr       (p11tool_opt_strs+2875)
#define zExplain        (p11tool_opt_strs+2894)
#define zDetail         (p11tool_opt_strs+2897)
#define zFullVersion    (p11tool_opt_strs+3153)
/* extracted from optcode.tlib near line 315 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE | OPTPROC_NXLAT_OPT
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define p11tool_full_usage (NULL)

#define p11tool_short_usage (p11tool_opt_strs+3168)

/*
 *  Create the static procedure(s) declared above.
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    (void)pOptions;
    USAGE(P11TOOL_EXIT_SUCCESS);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the debug option.
 */
static void
doOptDebug(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0 ,  9999 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:

    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the load-privkey option.
 */
static void
doOptLoad_Privkey(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static teOptFileType const  type =
        FTYPE_MODE_MUST_EXIST + FTYPE_MODE_NO_OPEN;
    static tuFileMode           mode;
#ifndef O_CLOEXEC
#  define O_CLOEXEC 0
#endif
    mode.file_flags = O_CLOEXEC;

    optionFileCheck(pOptions, pOptDesc, type, mode);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the load-pubkey option.
 */
static void
doOptLoad_Pubkey(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static teOptFileType const  type =
        FTYPE_MODE_MUST_EXIST + FTYPE_MODE_NO_OPEN;
    static tuFileMode           mode;
#ifndef O_CLOEXEC
#  define O_CLOEXEC 0
#endif
    mode.file_flags = O_CLOEXEC;

    optionFileCheck(pOptions, pOptDesc, type, mode);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the load-certificate option.
 */
static void
doOptLoad_Certificate(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static teOptFileType const  type =
        FTYPE_MODE_MUST_EXIST + FTYPE_MODE_NO_OPEN;
    static tuFileMode           mode;
#ifndef O_CLOEXEC
#  define O_CLOEXEC 0
#endif
    mode.file_flags = O_CLOEXEC;

    optionFileCheck(pOptions, pOptDesc, type, mode);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the inraw option.
 */
static void
doOptInraw(tOptions* pOptions, tOptDesc* pOptDesc)
{
    int res = optionAlias(pOptions, pOptDesc, INDEX_OPT_INDER);
    if ((res != 0) && ((pOptions->fOptSet & OPTPROC_ERRSTOP) != 0))
        USAGE(P11TOOL_EXIT_FAILURE);

}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the provider option.
 */
static void
doOptProvider(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static teOptFileType const  type =
        FTYPE_MODE_MUST_EXIST + FTYPE_MODE_NO_OPEN;
    static tuFileMode           mode;
#ifndef O_CLOEXEC
#  define O_CLOEXEC 0
#endif
    mode.file_flags = O_CLOEXEC;

    optionFileCheck(pOptions, pOptDesc, type, mode);
}
/* extracted from optmain.tlib near line 1133 */

#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

#ifndef  WITH_PACKAGER
# define p11tool_packager_info NULL
#else
static char const p11tool_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport p11tool bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif

tOptions p11toolOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_NEGATIONS
    + OPTPROC_REORDER
    + OPTPROC_GNUUSAGE
    + OPTPROC_MISUSE ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      NO_EQUIVALENT, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      NO_EQUIVALENT /* index of default opt */
    },
    34 /* full option count */, 31 /* user option count */,
    p11tool_full_usage, p11tool_short_usage,
    NULL, NULL,
    PKGDATADIR, p11tool_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char* AO_gettext(char const* pz);
static void  coerce_it(void** s);

static char*
AO_gettext(char const* pz)
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup(pzRes);
    if (pzRes == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(P11TOOL_EXIT_FAILURE);
    }
    return pzRes;
}

static void coerce_it(void** s) { *s = AO_gettext(*s);
}

/*
 *  This invokes the translation code (e.g. gettext(3)).
 */
static void
translate_option_strings(void)
{
    tOptions * const pOpt = &p11toolOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * pOD = pOpt->pOptDesc;
        char **    ppz = (char**)(void*)&(option_usage_text);
        int        ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);

        coerce_it((void*)&(pOpt->pzCopyright));
        coerce_it((void*)&(pOpt->pzCopyNotice));
        coerce_it((void*)&(pOpt->pzFullVersion));
        coerce_it((void*)&(pOpt->pzUsageTitle));
        coerce_it((void*)&(pOpt->pzExplain));
        coerce_it((void*)&(pOpt->pzDetail));
        coerce_it((void*)&(pOpt->pzPackager));
        coerce_it((void*)&(pOpt->pzShortUsage));
        option_usage_text.field_ct = 0;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++)
            coerce_it((void*)&(pOD->pzText));
    }

    if ((pOpt->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * pOD = pOpt->pOptDesc;
        int        ix;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++) {
            coerce_it((void*)&(pOD->pz_Name));
            coerce_it((void*)&(pOD->pz_DisableName));
            coerce_it((void*)&(pOD->pz_DisablePfx));
        }
        /* prevent re-translation */
        p11toolOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
/* p11tool-args.c ends here */
